# Essential basic functionality

In [39]:
import numpy as np

In [40]:
import pandas as pd

In [41]:
index = pd.date_range("1/1/2000", periods=8)

In [42]:
index

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')

In [43]:
index2 = pd.date_range("1/1/2000", periods=8,freq='M')

In [44]:
index2

DatetimeIndex(['2000-01-31', '2000-02-29', '2000-03-31', '2000-04-30',
               '2000-05-31', '2000-06-30', '2000-07-31', '2000-08-31'],
              dtype='datetime64[ns]', freq='M')

In [45]:
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])

In [46]:
s

a   -1.405603
b   -0.897936
c   -0.660885
d    1.755417
e    0.148828
dtype: float64

In [47]:
df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=["A", "B", "C"])

In [48]:
df

A         B         C
2000-01-01  0.459253 -0.525373  1.124116
2000-01-02  0.328501  0.742063 -1.680669
2000-01-03  0.758567 -1.359896  0.048292
2000-01-04  1.553641  0.378608 -0.121617
2000-01-05  0.207323  1.261774 -0.545756
2000-01-06  1.352899  0.672543 -0.211561
2000-01-07  0.395342  0.300007  1.157092
2000-01-08  0.781457 -1.404341  0.141357

In [49]:
long_series = pd.Series(np.random.randn(1000))

In [50]:
long_series.head()

0    0.428035
1    0.415150
2    0.345762
3    0.207961
4   -1.074859
dtype: float64

In [51]:
long_series.tail(3)

997   -1.570035
998   -0.265669
999   -2.320876
dtype: float64

## Attributes and underlying data

In [52]:
df[:2]

A         B         C
2000-01-01  0.459253 -0.525373  1.124116
2000-01-02  0.328501  0.742063 -1.680669

In [53]:
index

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')

In [54]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [55]:
for x in df.columns:
    print(x.lower())

a
b
c


In [56]:
df.columns = [x.lower() for x in df.columns ]

In [57]:
df.columns

Index(['a', 'b', 'c'], dtype='object')

In [58]:
df.columns = [x.upper() for x in df.columns ]

In [59]:
df

A         B         C
2000-01-01  0.459253 -0.525373  1.124116
2000-01-02  0.328501  0.742063 -1.680669
2000-01-03  0.758567 -1.359896  0.048292
2000-01-04  1.553641  0.378608 -0.121617
2000-01-05  0.207323  1.261774 -0.545756
2000-01-06  1.352899  0.672543 -0.211561
2000-01-07  0.395342  0.300007  1.157092
2000-01-08  0.781457 -1.404341  0.141357

In [60]:
s.array

<PandasArray>
[-1.4056026131406136, -0.8979355707620631, -0.6608851917837442,
  1.7554166511625455,  0.1488278821131381]
Length: 5, dtype: float64

In [61]:
s.index.array

<PandasArray>
['a', 'b', 'c', 'd', 'e']
Length: 5, dtype: object

In [62]:
s.to_numpy()

array([-1.40560261, -0.89793557, -0.66088519,  1.75541665,  0.14882788])

In [63]:
np.asarray(s)

array([-1.40560261, -0.89793557, -0.66088519,  1.75541665,  0.14882788])

In [64]:
ser = pd.Series(pd.date_range("2000", periods=2, tz="CET"))

In [65]:
ser.to_numpy(dtype=object)

array([Timestamp('2000-01-01 00:00:00+0100', tz='CET', freq='D'),
       Timestamp('2000-01-02 00:00:00+0100', tz='CET', freq='D')],
      dtype=object)

In [66]:
ser

0   2000-01-01 00:00:00+01:00
1   2000-01-02 00:00:00+01:00
dtype: datetime64[ns, CET]

In [67]:
ser.to_numpy(dtype="datetime64[ns]")

array(['1999-12-31T23:00:00.000000000', '2000-01-01T23:00:00.000000000'],
      dtype='datetime64[ns]')

In [68]:
df.to_numpy()

array([[ 0.4592529 , -0.52537306,  1.12411646],
       [ 0.32850105,  0.74206298, -1.68066942],
       [ 0.75856694, -1.35989607,  0.04829201],
       [ 1.55364104,  0.37860846, -0.12161711],
       [ 0.20732289,  1.26177426, -0.54575618],
       [ 1.35289881,  0.67254321, -0.21156091],
       [ 0.39534179,  0.30000683,  1.15709185],
       [ 0.78145733, -1.40434141,  0.14135733]])