# Essential basic functionality

In [69]:
import numpy as np

In [70]:
import pandas as pd

In [71]:
index = pd.date_range("1/1/2000", periods=8)

In [72]:
index

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')

In [73]:
index2 = pd.date_range("1/1/2000", periods=8,freq='M')

In [74]:
index2

DatetimeIndex(['2000-01-31', '2000-02-29', '2000-03-31', '2000-04-30',
               '2000-05-31', '2000-06-30', '2000-07-31', '2000-08-31'],
              dtype='datetime64[ns]', freq='M')

In [75]:
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])

In [76]:
s

a    0.660581
b    0.097539
c    0.411723
d   -1.214195
e    1.538296
dtype: float64

In [77]:
df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=["A", "B", "C"])

In [78]:
df

A         B         C
2000-01-01 -1.555927  1.824400 -0.103888
2000-01-02  2.493311 -2.218632 -1.834097
2000-01-03  0.014749 -1.324293 -1.037334
2000-01-04 -0.727935 -1.949508 -2.324727
2000-01-05  1.113019  0.030672 -0.262045
2000-01-06  0.468949 -1.009396 -0.487583
2000-01-07 -0.395357  0.599188 -1.038343
2000-01-08 -0.458874 -1.032597  0.984219

In [79]:
long_series = pd.Series(np.random.randn(1000))

In [80]:
long_series.head()

0   -0.604606
1    0.253185
2    0.071653
3    1.726399
4   -0.305076
dtype: float64

In [81]:
long_series.tail(3)

997    0.063076
998   -0.456126
999   -0.460023
dtype: float64

## Attributes and underlying data

In [82]:
df[:2]

A         B         C
2000-01-01 -1.555927  1.824400 -0.103888
2000-01-02  2.493311 -2.218632 -1.834097

In [83]:
index

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')

In [84]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [85]:
for x in df.columns:
    print(x.lower())

a
b
c


In [86]:
df.columns = [x.lower() for x in df.columns ]

In [87]:
df.columns

Index(['a', 'b', 'c'], dtype='object')

In [88]:
df.columns = [x.upper() for x in df.columns ]

In [89]:
df

A         B         C
2000-01-01 -1.555927  1.824400 -0.103888
2000-01-02  2.493311 -2.218632 -1.834097
2000-01-03  0.014749 -1.324293 -1.037334
2000-01-04 -0.727935 -1.949508 -2.324727
2000-01-05  1.113019  0.030672 -0.262045
2000-01-06  0.468949 -1.009396 -0.487583
2000-01-07 -0.395357  0.599188 -1.038343
2000-01-08 -0.458874 -1.032597  0.984219

In [90]:
s.array

<PandasArray>
[ 0.6605811171703322, 0.09753942253614906,  0.4117229849406213,
 -1.2141952525365853,  1.5382955982354862]
Length: 5, dtype: float64

In [91]:
s.index.array

<PandasArray>
['a', 'b', 'c', 'd', 'e']
Length: 5, dtype: object

In [92]:
s.to_numpy()

array([ 0.66058112,  0.09753942,  0.41172298, -1.21419525,  1.5382956 ])

In [93]:
np.asarray(s)

array([ 0.66058112,  0.09753942,  0.41172298, -1.21419525,  1.5382956 ])

In [94]:
ser = pd.Series(pd.date_range("2000", periods=2, tz="CET"))

In [95]:
ser.to_numpy(dtype=object)

array([Timestamp('2000-01-01 00:00:00+0100', tz='CET', freq='D'),
       Timestamp('2000-01-02 00:00:00+0100', tz='CET', freq='D')],
      dtype=object)

In [96]:
ser

0   2000-01-01 00:00:00+01:00
1   2000-01-02 00:00:00+01:00
dtype: datetime64[ns, CET]

In [97]:
ser.to_numpy(dtype="datetime64[ns]")

array(['1999-12-31T23:00:00.000000000', '2000-01-01T23:00:00.000000000'],
      dtype='datetime64[ns]')

In [98]:
df.to_numpy()

array([[-1.55592667,  1.82439962, -0.1038883 ],
       [ 2.49331091, -2.21863156, -1.83409701],
       [ 0.01474852, -1.32429338, -1.0373337 ],
       [-0.72793537, -1.94950773, -2.32472689],
       [ 1.11301925,  0.030672  , -0.26204463],
       [ 0.46894915, -1.00939615, -0.48758306],
       [-0.39535657,  0.59918809, -1.03834252],
       [-0.45887431, -1.03259664,  0.98421918]])

## Accelerated operations

pandas通过numexpr和bottleneck两种类库来pandas的某些二进制和布尔类型

In [100]:
pd.set_option("compute.use_bottleneck",False)

In [101]:
pd.set_option("compute.use_numexpr",False)

## Matching / broadcasting behavior

DataFrame有add（）、sub（）、mul（）、div（）方法和相关函数radd（）、rsub（）、…   
用于执行二进制操作。对于广播行为，序列输入是最重要的。   
使用这些函数，您可以使用来通过axis关键字匹配索引或列：

In [112]:
df = pd.DataFrame({"one":pd.Series([1,2,3], index=["a","b","c"]),"two":pd.Series([2,3,4,4], index=["a","b","c","d"]),"three":pd.Series([3,2,5], index=["b","c","d"]),})

In [113]:
df

one  two  three
a  1.0    2    NaN
b  2.0    3    3.0
c  3.0    4    2.0
d  NaN    4    5.0

In [114]:
row = df.iloc[1] #取第二行

In [115]:
row

one      2.0
two      3.0
three    3.0
Name: b, dtype: float64

In [119]:
column = df["two"] #取第二列

In [120]:
column

a    2
b    3
c    4
d    4
Name: two, dtype: int64

In [122]:
df.sub(row, axis="columns") #用df逐行减去row,如df的第一行a 1.0 2 NaN 减去row的2.0 3.0 3.0

one  two  three
a -1.0 -1.0    NaN
b  0.0  0.0    0.0
c  1.0  1.0   -1.0
d  NaN  1.0    2.0

In [123]:
df.sub(row, axis=1)

one  two  three
a -1.0 -1.0    NaN
b  0.0  0.0    0.0
c  1.0  1.0   -1.0
d  NaN  1.0    2.0

In [124]:
df.sub(column, axis="index")

one  two  three
a -1.0    0    NaN
b -1.0    0    0.0
c -1.0    0   -2.0
d  NaN    0    1.0

In [125]:
df.sub(column, axis=0)

one  two  three
a -1.0    0    NaN
b -1.0    0    0.0
c -1.0    0   -2.0
d  NaN    0    1.0

DataFrame.sub(other, axis='columns', level=None, fill_value=None) 

获取DataFrame和其他元素的减法（二进制运算符sub）。  
与等效，但支持用fill_value替换输入之一中的丢失数据。rsub是反向版本。dataframe - other  
在灵活的包装器（add，sub，mul，div，mod，pow）中使用算术运算符：+，-，*，/，//，％，**。  

<font color='red'><strong>
axis ：{0 或‘index’, 1 或‘columns’}
是按索引(0或' index ')还是按列(1或' columns ')进行比较。
对于Series输入，轴匹配Series索引。
</strong></font>

level ：int 或 label 跨级别广播，匹配通过的多索引级别上的索引值。

fill_value ：float 或 None, 默认为 None
在计算之前，用这个值填充现有的NaN值，
以及成功的DataFrame对齐所需的任何新元素。
如果两个对应的DataFrame位置中的数据丢失，
则结果将丢失。