# Essential basic functionality

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
index = pd.date_range("1/1/2000", periods=8)

In [4]:
index

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')

In [5]:
index2 = pd.date_range("1/1/2000", periods=8,freq='M')

In [6]:
index2

DatetimeIndex(['2000-01-31', '2000-02-29', '2000-03-31', '2000-04-30',
               '2000-05-31', '2000-06-30', '2000-07-31', '2000-08-31'],
              dtype='datetime64[ns]', freq='M')

In [7]:
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])

In [8]:
s

a   -3.165381
b   -0.836738
c    0.611968
d    0.385082
e   -2.094265
dtype: float64

In [9]:
df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=["A", "B", "C"])

In [10]:
df

A         B         C
2000-01-01  0.844096 -1.029971 -0.149505
2000-01-02 -0.132629  2.408868  0.504614
2000-01-03  0.249322  0.111271  0.029254
2000-01-04 -0.989747 -1.296351  0.495621
2000-01-05 -0.371673  0.841933  1.191621
2000-01-06  2.468196 -0.979006  0.149412
2000-01-07  0.118431  0.782076  0.484149
2000-01-08  0.146707 -0.616597 -1.123213

In [11]:
long_series = pd.Series(np.random.randn(1000))

In [12]:
long_series.head()

0   -0.849467
1   -0.448309
2    0.745838
3    1.016724
4    0.568535
dtype: float64

In [13]:
long_series.tail(3)

997    0.650001
998    0.278652
999    1.385526
dtype: float64

## Attributes and underlying data

In [14]:
df[:2]

A         B         C
2000-01-01  0.844096 -1.029971 -0.149505
2000-01-02 -0.132629  2.408868  0.504614

In [15]:
index

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')

In [16]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [17]:
for x in df.columns:
    print(x.lower())

a
b
c


In [18]:
df.columns = [x.lower() for x in df.columns ]

In [19]:
df.columns

Index(['a', 'b', 'c'], dtype='object')

In [20]:
df.columns = [x.upper() for x in df.columns ]

In [21]:
df

A         B         C
2000-01-01  0.844096 -1.029971 -0.149505
2000-01-02 -0.132629  2.408868  0.504614
2000-01-03  0.249322  0.111271  0.029254
2000-01-04 -0.989747 -1.296351  0.495621
2000-01-05 -0.371673  0.841933  1.191621
2000-01-06  2.468196 -0.979006  0.149412
2000-01-07  0.118431  0.782076  0.484149
2000-01-08  0.146707 -0.616597 -1.123213

In [22]:
s.array

<PandasArray>
[-3.1653808267202925, -0.8367381958938441,  0.6119680614196744,
  0.3850824682298342, -2.0942653454547178]
Length: 5, dtype: float64

In [23]:
s.index.array

<PandasArray>
['a', 'b', 'c', 'd', 'e']
Length: 5, dtype: object

In [24]:
s.to_numpy()

array([-3.16538083, -0.8367382 ,  0.61196806,  0.38508247, -2.09426535])

In [25]:
np.asarray(s)

array([-3.16538083, -0.8367382 ,  0.61196806,  0.38508247, -2.09426535])

In [26]:
ser = pd.Series(pd.date_range("2000", periods=2, tz="CET"))

In [27]:
ser.to_numpy(dtype=object)

array([Timestamp('2000-01-01 00:00:00+0100', tz='CET', freq='D'),
       Timestamp('2000-01-02 00:00:00+0100', tz='CET', freq='D')],
      dtype=object)

In [28]:
ser

0   2000-01-01 00:00:00+01:00
1   2000-01-02 00:00:00+01:00
dtype: datetime64[ns, CET]

In [29]:
ser.to_numpy(dtype="datetime64[ns]")

array(['1999-12-31T23:00:00.000000000', '2000-01-01T23:00:00.000000000'],
      dtype='datetime64[ns]')

In [30]:
df.to_numpy()

array([[ 0.84409638, -1.02997131, -0.14950501],
       [-0.13262902,  2.40886846,  0.50461406],
       [ 0.24932184,  0.11127124,  0.02925381],
       [-0.98974705, -1.29635149,  0.49562101],
       [-0.3716727 ,  0.84193297,  1.19162092],
       [ 2.46819577, -0.97900633,  0.14941155],
       [ 0.11843131,  0.78207628,  0.48414859],
       [ 0.14670655, -0.61659685, -1.12321323]])

## Accelerated operations

pandas通过numexpr和bottleneck两种类库来pandas的某些二进制和布尔类型

In [31]:
pd.set_option("compute.use_bottleneck",False)

In [32]:
pd.set_option("compute.use_numexpr",False)

## Matching / broadcasting behavior

DataFrame有add（）、sub（）、mul（）、div（）方法和相关函数radd（）、rsub（）、…   
用于执行二进制操作。对于广播行为，序列输入是最重要的。   
使用这些函数，您可以使用来通过axis关键字匹配索引或列：

In [33]:
df = pd.DataFrame({"one":pd.Series([1,2,3], index=["a","b","c"]),"two":pd.Series([2,3,4,4], index=["a","b","c","d"]),"three":pd.Series([3,2,5], index=["b","c","d"]),})

In [34]:
df

one  two  three
a  1.0    2    NaN
b  2.0    3    3.0
c  3.0    4    2.0
d  NaN    4    5.0

In [35]:
row = df.iloc[1] #取第二行

In [36]:
row

one      2.0
two      3.0
three    3.0
Name: b, dtype: float64

In [37]:
column = df["two"] #取第二列

In [38]:
column

a    2
b    3
c    4
d    4
Name: two, dtype: int64

In [39]:
df.sub(row, axis="columns") #用df逐行减去row,如df的第一行a 1.0 2 NaN 减去row的2.0 3.0 3.0

one  two  three
a -1.0 -1.0    NaN
b  0.0  0.0    0.0
c  1.0  1.0   -1.0
d  NaN  1.0    2.0

In [40]:
df.sub(row, axis=1)

one  two  three
a -1.0 -1.0    NaN
b  0.0  0.0    0.0
c  1.0  1.0   -1.0
d  NaN  1.0    2.0

In [41]:
df.sub(column, axis="index")

one  two  three
a -1.0    0    NaN
b -1.0    0    0.0
c -1.0    0   -2.0
d  NaN    0    1.0

In [42]:
df.sub(column, axis=0)

one  two  three
a -1.0    0    NaN
b -1.0    0    0.0
c -1.0    0   -2.0
d  NaN    0    1.0

DataFrame.sub(other, axis='columns', level=None, fill_value=None) 

获取DataFrame和其他元素的减法（二进制运算符sub）。  
与等效，但支持用fill_value替换输入之一中的丢失数据。rsub是反向版本。dataframe - other  
在灵活的包装器（add，sub，mul，div，mod，pow）中使用算术运算符：+，-，*，/，//，％，**。  

<font color='red'><strong>
axis ：{0 或‘index’, 1 或‘columns’}
是按索引(0或' index ')还是按列(1或' columns ')进行比较。
对于Series输入，轴匹配Series索引。
</strong></font>

level ：int 或 label 跨级别广播，匹配通过的多索引级别上的索引值。

fill_value ：float 或 None, 默认为 None
在计算之前，用这个值填充现有的NaN值，
以及成功的DataFrame对齐所需的任何新元素。
如果两个对应的DataFrame位置中的数据丢失，
则结果将丢失。

In [43]:
dfmi = df.copy()

In [44]:
dfmi

one  two  three
a  1.0    2    NaN
b  2.0    3    3.0
c  3.0    4    2.0
d  NaN    4    5.0

In [45]:
dfmi.index = pd.MultiIndex.from_tuples([(1,"a"),(2,"b"),(3,"c"),(4,"a")],names=["first", "second"])

In [46]:
dfmi.index

MultiIndex([(1, 'a'),
            (2, 'b'),
            (3, 'c'),
            (4, 'a')],
           names=['first', 'second'])

In [47]:
dfmi

one  two  three
first second                 
1     a       1.0    2    NaN
2     b       2.0    3    3.0
3     c       3.0    4    2.0
4     a       NaN    4    5.0

In [48]:
column

a    2
b    3
c    4
d    4
Name: two, dtype: int64

In [49]:
dfmi.sub(column, axis=0, level="second")

one  two  three
first second                 
1     a      -1.0    0    NaN
2     b      -1.0    0    0.0
3     c      -1.0    0   -2.0
4     a       NaN    2    3.0

In [50]:
s = pd.Series(np.arange(10))

In [51]:
s

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [52]:
div, rem = divmod(s, 3)

In [53]:
div # index value

0    0
1    0
2    0
3    1
4    1
5    1
6    2
7    2
8    2
9    3
dtype: int32

In [54]:
rem

0    0
1    1
2    2
3    0
4    1
5    2
6    0
7    1
8    2
9    0
dtype: int32

In [55]:
idx = pd.Index(np.arange(10))

In [56]:
idx

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [57]:
div, rem = divmod(idx, 3)

In [58]:
div

Int64Index([0, 0, 0, 1, 1, 1, 2, 2, 2, 3], dtype='int64')

In [59]:
rem

Int64Index([0, 1, 2, 0, 1, 2, 0, 1, 2, 0], dtype='int64')

In [60]:
div, rem = divmod(s, [2,2,3,3,4,4,5,5,6,6])

In [61]:
div

0    0
1    0
2    0
3    1
4    1
5    1
6    1
7    1
8    1
9    1
dtype: int32

In [62]:
rem

0    0
1    1
2    2
3    0
4    0
5    1
6    1
7    2
8    2
9    3
dtype: int32

## Missing data / operations with fill values

In [63]:
df

one  two  three
a  1.0    2    NaN
b  2.0    3    3.0
c  3.0    4    2.0
d  NaN    4    5.0

In [64]:
df2 = df

In [65]:
df2

one  two  three
a  1.0    2    NaN
b  2.0    3    3.0
c  3.0    4    2.0
d  NaN    4    5.0

In [66]:
df + df2

one  two  three
a  2.0    4    NaN
b  4.0    6    6.0
c  6.0    8    4.0
d  NaN    8   10.0

In [67]:
df.add(df2, fill_value=0)

one  two  three
a  2.0    4    NaN
b  4.0    6    6.0
c  6.0    8    4.0
d  NaN    8   10.0

## Flexible comparisons

Series和DataFrame具有二进制比较方法eq、ne、lt、gt、le和ge，其行为类似于上述二进制算术运算：

In [68]:
df.gt(df2)

one    two  three
a  False  False  False
b  False  False  False
c  False  False  False
d  False  False  False

In [69]:
df2.ne(df)

one    two  three
a  False  False   True
b  False  False  False
c  False  False  False
d   True  False  False

## Boolean reductions

你可以用empty、any（）、all（）和bool（）来提供汇总布尔结果

In [70]:
(df > 0).all()

one      False
two       True
three    False
dtype: bool

In [71]:
(df > 0).any()

one      True
two      True
three    True
dtype: bool

In [72]:
(df > 0).any().any()

True

In [73]:
df.empty

False

In [74]:
pd.DataFrame(columns=list("ABC")).empty

True

In [75]:
pd.Series([True]).bool()

True

In [76]:
pd.Series([False]).bool()

False

In [77]:
pd.DataFrame([True]).bool()

True

In [78]:
pd.DataFrame([False]).bool()

False

## Comparing if objects are equivalent

In [79]:
df + df == df * 2

one   two  three
a   True  True  False
b   True  True   True
c   True  True   True
d  False  True   True

In [80]:
(df + df == df * 2).all()

one      False
two       True
three    False
dtype: bool

In [81]:
np.nan == np.nan

False

In [82]:
(df + df).equals(df * 2)

True

In [83]:
df1 = pd.DataFrame({"col":["foo", 0 , np.nan]})

In [84]:
df2 = pd.DataFrame({"col":[np.nan, 0, "foo"]}, index=[2, 1, 0])

In [85]:
df1.equals(df2)

False

In [86]:
df1.equals(df2.sort_index())

True

## Comparing array-like objects

In [87]:
pd.Series(["foo","bar","baz"]) == "foo"

0     True
1    False
2    False
dtype: bool

In [88]:
pd.Index(["foo","bar","baz"]) == "foo"

array([ True, False, False])

In [89]:
pd.Series(["foo","bar","baz"]) == pd.Index(["foo","bar","qux"])

0     True
1     True
2    False
dtype: bool

In [90]:
pd.Series(["foo","bar","baz"]) == np.array(["foo","bar","qux"])

0     True
1     True
2    False
dtype: bool

In [91]:
# pd.Series(['foo', 'bar', 'baz']) == pd.Series(['foo', 'bar'])
## 报错! ValueError: Can only compare identically-labeled Series objects

In [92]:
# pd.Series(['foo', 'bar', 'baz']) == pd.Series(['foo'])
## 报错! ValueError: Can only compare identically-labeled Series objects

In [93]:
np.array([1, 2, 3]) == np.array([2])

array([False,  True, False])

In [94]:
np.array([1, 2, 3]) == np.array([1, 2])

c:\users\zhangyanqing\.conda\envs\tf2.0\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

## Combining overlapping data sets

In [95]:
df1 = pd.DataFrame({"A":[1.0, np.nan, 3.0, 5.0, np.nan], "B":[np.nan, 2.0, 3.0, np.nan, 6.0]})

In [96]:
df2 = pd.DataFrame({"A":[5.0, 2.0, 4.0, np.nan,3.0, 7.0], "B":[np.nan, np.nan, 3.0, 4.0, 6.0, 8.0]})

In [97]:
df1

A    B
0  1.0  NaN
1  NaN  2.0
2  3.0  3.0
3  5.0  NaN
4  NaN  6.0

In [98]:
df2

A    B
0  5.0  NaN
1  2.0  NaN
2  4.0  3.0
3  NaN  4.0
4  3.0  6.0
5  7.0  8.0

In [99]:
df1.combine_first(df2)

A    B
0  1.0  NaN
1  2.0  2.0
2  3.0  3.0
3  5.0  4.0
4  3.0  6.0
5  7.0  8.0

## Descriptive statistics

In [100]:
df

one  two  three
a  1.0    2    NaN
b  2.0    3    3.0
c  3.0    4    2.0
d  NaN    4    5.0

In [101]:
df.mean(0)

one      2.000000
two      3.250000
three    3.333333
dtype: float64

In [102]:
df.mean(1)

a    1.500000
b    2.666667
c    3.000000
d    4.500000
dtype: float64

In [103]:
df.sum(0, skipna=False)

one       NaN
two      13.0
three     NaN
dtype: float64

In [104]:
df.sum(axis=1,skipna=True)

a    3.0
b    8.0
c    9.0
d    9.0
dtype: float64

In [105]:
ts_stand = (df - df.mean()) / df.std()

In [106]:
ts_stand.std()

one      1.0
two      1.0
three    1.0
dtype: float64

In [107]:
xs_stand = df.sub(df.mean(1), axis=0).div(df.std(1), axis=0)

In [108]:
xs_stand.std(1)

a    1.0
b    1.0
c    1.0
d    1.0
dtype: float64

In [109]:
df.cumsum()

one  two  three
a  1.0    2    NaN
b  3.0    5    3.0
c  6.0    9    5.0
d  NaN   13   10.0

In [110]:
np.mean(df["one"])

2.0

In [111]:
np.mean(df["one"].to_numpy())

nan

In [112]:
series = pd.Series(np.random.randn(50))

In [113]:
series[20:500] = np.nan

In [114]:
series[10:20] = 5

In [115]:
series.nunique()

11

## General DataFrame combin

In [116]:
def combiner(x, y):
    return np.where(pd.isna(x), y, x)

In [117]:
df1.combine(df2, combiner)

A    B
0  1.0  NaN
1  2.0  2.0
2  3.0  3.0
3  5.0  4.0
4  3.0  6.0
5  7.0  8.0

## Descriptive statistics

In [118]:
df

one  two  three
a  1.0    2    NaN
b  2.0    3    3.0
c  3.0    4    2.0
d  NaN    4    5.0

In [119]:
df.mean(0)

one      2.000000
two      3.250000
three    3.333333
dtype: float64

In [120]:
df.mean(1)

a    1.500000
b    2.666667
c    3.000000
d    4.500000
dtype: float64

In [121]:
df.sum(0, skipna=False)

one       NaN
two      13.0
three     NaN
dtype: float64

In [122]:
df.sum(axis=1,skipna=True)

a    3.0
b    8.0
c    9.0
d    9.0
dtype: float64

In [123]:
ts_stand = (df - df.mean() / df.std())

In [124]:
ts_stand.std()

one      1.000000
two      0.957427
three    1.527525
dtype: float64

In [125]:
xs_stand = df.sub(df.mean(1), axis=0).div(df.std(1), axis=0)

In [126]:
xs_stand.std(1)

a    1.0
b    1.0
c    1.0
d    1.0
dtype: float64

In [127]:
df.cumsum()

one  two  three
a  1.0    2    NaN
b  3.0    5    3.0
c  6.0    9    5.0
d  NaN   13   10.0

In [128]:
np.mean(df["one"])

2.0

In [129]:
np.mean(df["one"].to_numpy())

nan

In [130]:
series = pd.Series(np.random.randn(500))

In [131]:
series[200:500] = np.nan

In [132]:
series[10:20] = 5

In [133]:
series.nunique()

191

|  函数名   | 作用说明  |
|  ----  | ----  |
| count | Number of non-NA observations |
| sum | Sum of values |
| mean | Mean of values |
| mad | Mean absolute deviation |
| median | Arithmetic median of values |
| min | Minimum |
| max | Maximum |
| mode | Mode |
| abs | Absolute Value |
| prod | Product of values |
| std | Bessel-corrected sample standard deviation |
| var | Unbiased variance |
| sem | Standard error of the mean |
| skew | Sample skewness (3rd moment) |
| kurt | Sample kurtosis (4th moment) |
| quantile | Sample quantile (value at %) |
| cumsum | Cumulative sum |
| cumprod | Cumulative product |
| cummax | Cumulative maximum |
| cummin | Cumulative minimum |

## Summarizing data: describe

describe()函数用于计算各种汇总统计信息，关于Series和columns的（当然Na的除外）

In [134]:
series = pd.Series(np.random.randn(1000))

In [135]:
series[::2] = np.nan

In [136]:
series.describe()

count    500.000000
mean      -0.073145
std        1.001435
min       -2.746230
25%       -0.774329
50%       -0.056167
75%        0.590763
max        2.778282
dtype: float64

In [137]:
frame = pd.DataFrame(np.random.randn(1000,5), columns=["a","b","c","d","e"])

In [138]:
frame.iloc[::2] = np.nan

In [139]:
frame.describe()

a           b           c           d           e
count  500.000000  500.000000  500.000000  500.000000  500.000000
mean    -0.045690    0.014641    0.034640   -0.043776    0.036312
std      0.984603    1.010414    0.984741    1.007903    0.997040
min     -3.095315   -3.273730   -3.102571   -2.698486   -3.813330
25%     -0.677529   -0.676742   -0.558817   -0.655521   -0.610863
50%     -0.085495    0.028001    0.058961   -0.130058    0.073312
75%      0.598799    0.677019    0.666645    0.666351    0.673597
max      2.655738    2.870373    3.088348    2.945976    3.291694

In [140]:
series.describe(percentiles=[0.05,0.25,0.75,0.95])

count    500.000000
mean      -0.073145
std        1.001435
min       -2.746230
5%        -1.726467
25%       -0.774329
50%       -0.056167
75%        0.590763
95%        1.626609
max        2.778282
dtype: float64

In [141]:
s = pd.Series(["a", "a", "b", "b", "a", "a", np.nan, "c", "d", "a"])

In [142]:
s.describe()

count     9
unique    4
top       a
freq      5
dtype: object

In [143]:
frame = pd.DataFrame({"a":["Yes","Yes","No","No"],"b":range(4)})

In [144]:
frame.describe()

b
count  4.000000
mean   1.500000
std    1.290994
min    0.000000
25%    0.750000
50%    1.500000
75%    2.250000
max    3.000000

In [145]:
frame.describe(include=["object"])

a
count     4
unique    2
top     Yes
freq      2

In [146]:
frame.describe(include=["number"])

b
count  4.000000
mean   1.500000
std    1.290994
min    0.000000
25%    0.750000
50%    1.500000
75%    2.250000
max    3.000000

In [147]:
frame.describe(include="all")

a         b
count     4  4.000000
unique    2       NaN
top     Yes       NaN
freq      2       NaN
mean    NaN  1.500000
std     NaN  1.290994
min     NaN  0.000000
25%     NaN  0.750000
50%     NaN  1.500000
75%     NaN  2.250000
max     NaN  3.000000

## Index of min/max values

In [150]:
s1 = pd.Series(np.random.randn(5))

In [151]:
s1

0    0.597793
1   -0.330796
2   -1.673096
3    0.142446
4    1.217835
dtype: float64

In [153]:
s1.idxmin(),s1.idxmax()

(2, 4)

In [154]:
df1 = pd.DataFrame(np.random.randn(5,3), columns=["A","B","C"])

In [155]:
df1

A         B         C
0  0.531692  0.751615 -2.090817
1 -1.157355 -0.862565 -0.645174
2 -0.344476 -0.373331  0.192011
3  0.052135  0.282145  0.074104
4  1.105806  1.384213  0.016238

In [156]:
df1.idxmin(axis=0)

A    1
B    1
C    0
dtype: int64

In [157]:
df1.idxmax(axis=1)

0    B
1    C
2    C
3    B
4    B
dtype: object

In [158]:
df3 = pd.DataFrame([2, 1, 1, 3, np.nan], columns=["A"], index=list("edcba"))

In [159]:
df3

A
e  2.0
d  1.0
c  1.0
b  3.0
a  NaN

In [160]:
df3["A"].idxmin()

'd'